import type { Project, PropertyType } from "./types";

export const CITIES = ["Kochi", "Pune", "Bengaluru", "Goa"] as const;
export type City = typeof CITIES[number];

export const PROPERTY_TYPES: PropertyType[] = ["Apartment", "Villa", "Plot"];

export const POPULAR_BY_CITY: Record<City, Project[]> = {
  Kochi: [
    {
      id: "ko-1",
      slug: "kochi-skyline-apartments",
      title: "2 BHK Apartments at Skyline Apartments",
      city: "Kochi",
      location: "Kakkanad, Kochi",
      price: 52000000,
      priceStr: "5.2Cr",
      bedrooms: 2,
      areaSqft: 980,
      image:
        "https://images.unsplash.com/photo-1494526585095-c41746248156?q=80&w=1200&auto=format&fit=crop",
      logo: "/images/builders/builder1.png",
      type: "Apartment",
    },
    {
      id: "ko-2",
      slug: "kochi-marina-residences",
      title: "3 BHK Apartments at Shobha Marina One",
      city: "Kochi",
      location: "Marine Drive, Kochi",
      price: 89000000,
      priceStr: "8.9Cr",
      bedrooms: 3,
      areaSqft: 1450,
      image:
        "https://images.unsplash.com/photo-1460317442991-0ec209397118?q=80&w=1200&auto=format&fit=crop",
      logo: "/images/builders/builder2.png",
      type: "Apartment",
    },
    {
      id: "ko-3",
      slug: "kochi-greens-villas",
      title: "4 BHK Villas at Greens Villas",
      city: "Kochi",
      location: "Edappally, Kochi",
      price: 125000000,
      priceStr: "12.5Cr",
      bedrooms: 4,
      areaSqft: 2100,
      image:
        "https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=1200&auto=format&fit=crop",
      logo: "/images/builders/builder3.png",
      type: "Villa",
    },
    {
      id: "ko-1",
      slug: "kochi-skyline-apartments",
      title: "2 BHK Apartments at Skyline Apartments",
      city: "Kochi",
      location: "Kakkanad, Kochi",
      price: 52000000,
      priceStr: "5.2Cr",
      bedrooms: 2,
      areaSqft: 980,
      image:
        "https://images.unsplash.com/photo-1494526585095-c41746248156?q=80&w=1200&auto=format&fit=crop",
      logo: "/images/builders/builder1.png",
      type: "Apartment",
    },
    {
      id: "ko-2",
      slug: "kochi-marina-residences",
      title: "3 BHK Apartments at Marina Residences",
      city: "Kochi",
      location: "Marine Drive, Kochi",
      price: 89000000,
      priceStr: "8.9Cr",
      bedrooms: 3,
      areaSqft: 1450,
      image:
        "https://images.unsplash.com/photo-1460317442991-0ec209397118?q=80&w=1200&auto=format&fit=crop",
      logo: "/images/builders/builder2.png",
      type: "Apartment",
    },
    {
      id: "ko-3",
      slug: "kochi-greens-villas",
      title: "4 BHK Villas at Greens Villas",
      city: "Kochi",
      location: "Edappally, Kochi",
      price: 12500000,
      priceStr: "12.5Cr",
      bedrooms: 4,
      areaSqft: 2100,
      image:
        "https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=1200&auto=format&fit=crop",
      logo: "/images/builders/builder3.png",
      type: "Villa",
    },
    {
      id: "ko-2",
      slug: "kochi-marina-residences",
      title: "3 BHK Apartments at Marina Residences",
      city: "Kochi",
      location: "Marine Drive, Kochi",
      price: 89000000,
      priceStr: "8.9Cr",
      bedrooms: 3,
      areaSqft: 1450,
      image:
        "https://images.unsplash.com/photo-1460317442991-0ec209397118?q=80&w=1200&auto=format&fit=crop",
      logo: "/images/builders/builder2.png",
      type: "Apartment",
    },
    {
      id: "ko-3",
      slug: "kochi-greens-villas",
      title: "4 BHK Villas at Greens Villas",
      city: "Kochi",
      location: "Edappally, Kochi",
      price: 12500000,
      priceStr: "1.25Cr",
      bedrooms: 4,
      areaSqft: 2100,
      image:
        "https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=1200&auto=format&fit=crop",
      logo: "/images/builders/builder3.png",
      type: "Villa",
    },
  ],
  Pune: [
    {
      id: "pu-1",
      slug: "pune-hillcrest",
      title: "2 BHK Apartments at Hillcrest Homes",
      city: "Pune",
      location: "Baner, Pune",
      price: 74000000,
      priceStr: "7.4Cr",
      bedrooms: 2,
      areaSqft: 1050,
      image:
        "https://images.unsplash.com/photo-1534237710431-e2fc698436d0?q=80&w=1200&auto=format&fit=crop",
      logo: "/images/builders/builder1.png",
      type: "Apartment",
    },
    {
      id: "pu-2",
      slug: "pune-lavish-villas",
      title: "4 BHK Villas at Lavish Villas",
      city: "Pune",
      location: "Hinjawadi, Pune",
      price: 18200000,
      priceStr: "1.82Cr",
      bedrooms: 4,
      areaSqft: 2400,
      image:
        "https://images.unsplash.com/photo-1560518883-ce09059eeffa?q=80&w=1200&auto=format&fit=crop",
      logo: "/images/builders/builder2.png",
      type: "Villa",
    },
    {
      id: "pu-3",
      slug: "pune-urban-plots",
      title: "Residential Plots at Urban Plots",
      city: "Pune",
      location: "Wagholi, Pune",
      price: 42000000,
      priceStr: "4.2Cr",
      bedrooms: 0,
      image:
        "https://images.unsplash.com/photo-1431576901776-e539bd916ba2?q=80&w=1200&auto=format&fit=crop",
      logo: "/images/builders/builder3.png",
      type: "Plot",
    },
    {
      id: "pu-1",
      slug: "pune-hillcrest",
      title: "2 BHK Apartments at Hillcrest Homes",
      city: "Pune",
      location: "Baner, Pune",
      price: 74000000,
      priceStr: "7.4Cr",
      bedrooms: 2,
      areaSqft: 1050,
      image:
        "https://images.unsplash.com/photo-1534237710431-e2fc698436d0?q=80&w=1200&auto=format&fit=crop",
      logo: "/images/builders/builder1.png",
      type: "Apartment",
    },
    {
      id: "pu-2",
      slug: "pune-lavish-villas",
      title: "4 BHK Villas at Lavish Villas",
      city: "Pune",
      location: "Hinjawadi, Pune",
      price: 18200000,
      priceStr: "1.82Cr",
      bedrooms: 4,
      areaSqft: 2400,
      image:
        "https://images.unsplash.com/photo-1560518883-ce09059eeffa?q=80&w=1200&auto=format&fit=crop",
      logo: "/images/builders/builder2.png",
      type: "Villa",
    },
    {
      id: "pu-3",
      slug: "pune-urban-plots",
      title: "Residential Plots at Urban Plots",
      city: "Pune",
      location: "Wagholi, Pune",
      price: 42000000,
      priceStr: "4.2Cr",
      bedrooms: 0,
      image:
        "https://images.unsplash.com/photo-1431576901776-e539bd916ba2?q=80&w=1200&auto=format&fit=crop",
      logo: "/images/builders/builder3.png",
      type: "Plot",
    },
    {
      id: "pu-3",
      slug: "pune-urban-plots",
      title: "Residential Plots at Urban Plots",
      city: "Pune",
      location: "Wagholi, Pune",
      price: 38500000,
      priceStr: "3.85Cr",
      bedrooms: 0,
      image:
        "https://images.unsplash.com/photo-1431576901776-e539bd916ba2?q=80&w=1200&auto=format&fit=crop",
      logo: "/images/builders/builder3.png",
      type: "Plot",
    },
    {
      id: "pu-1",
      slug: "pune-hillcrest",
      title: "2 BHK Apartments at Hillcrest Homes",
      city: "Pune",
      location: "Baner, Pune",
      price: 74000000,
      priceStr: "7.4Cr",
      bedrooms: 2,
      areaSqft: 1050,
      image:
        "https://images.unsplash.com/photo-1534237710431-e2fc698436d0?q=80&w=1200&auto=format&fit=crop",
      logo: "/images/builders/builder1.png",
      type: "Apartment",
    },
  ],
  Bengaluru: [],
  Goa: [],
};

export function formatINR(n: number) {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(n);
}
